name: Build and Test .NET Core Application

on:
  push:
    branches: ["main"]

jobs:

  restore:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore CircleERP.sln

  build:
    needs: restore
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Solution
        run: dotnet build CircleERP.sln --configuration ${{ matrix.configuration }}

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run Tests
        run: dotnet test CircleERP.Tests/CircleERP.Tests.csproj --no-build --verbosity normal

  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Client Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: CircleERP.client

      - name: Build Client
        run: npm run build
        working-directory: CircleERP.client

      - name: Run Client Tests
        run: npm run test
        working-directory: CircleERP.client